<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mimo
 * @package    Mimo (mimo.com)
 * @copyright  Copyright (c) 2011 Mimo (https://www.mimo.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * // this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
 * // onComplete: this.reloadChildren.bind(this)
 * //					parameters:'&'+Form.serialize($('payment[account_id]'))
 
 * checkout.setLoadWaiting('payment');
 * this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
 * onComplete: this.onComplete,
 * onFailure: checkout.ajaxFailure.bind(checkout),
 * checkout.setLoadWaiting(false)
 */
$_code	= $this->getMethodCode();
$url = $this->getAuthUrl();
?>
<style>
a.button{
display: block;
height: 19px;
border: 1px solid #DE5400;
background: #F18200;
padding: 0 8px;
font: bold 12px/19px Arial, Helvetica, sans-serif;
text-align: center;
white-space: nowrap;
color: white;
width: 135px;

}
</style>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li id="<?php echo $_code ?>_verify_key_btn_div">
			<!-- <button type="button" id="<?php echo $_code ?>_verify_key_btn" name="payment[verify_key_btn]" class="button" ><span><span><?php echo $this->__('Generate Oauth Key') ?></span></span></button>* -->
		<a href="<?php echo $url;?>"  class="button"  id="<?php echo $_code ?>_verify_key_btn" name="payment[verify_key_btn]"  ><?php echo $this->__('Generate Oauth Key') ?></a>
		</li>		
		<li id="<?php echo $_code ?>_verify_key_div">
			<label for="<?php echo $_code ?>_verify_key"><?php echo $this->__('Mimo Secure Payment Key (sent to email used with your Mimo account) : ') ?> <span class="required">*</span></label><br />
			<input type="text" id="<?php echo $_code ?>_verify_key" name="payment[verify_key]" title="<?php echo $this->__('Mimo Secure Payment Key') ?>" style="border:1px solid #8bc53f" class="required-entry input-text" value=""/>
		</li>
		<li>
			<?php

			 if($this->getQueryString()){
				$token = $this->requestToken($this->getQueryString());				
				Mage::getSingleton('core/session')->setTokenMage($token);
				$this->setToken($token);
				
				
			//	Mage::getSingleton('core/session')->setData($token);
				$amount=(strip_tags( $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())));
				$amount = round(str_replace("$","",$amount));
				
	//			$transaction = $this->transaction($amount);
			//	}
			
			}?>
		 		
		     		<span id="lblAccessCode">Your current Access Code for mimo is : <?php echo  $this->getQueryString(); ?><br/></span>
		    			
		    		<?php if(isset($token)){ 
		    						$this->setToken($token);
		    			?>
		     		<span id="lblAccessToken">Your current Access Token for mimo is : <?php echo $token; ?><br/></span> 
		 <?php }?>
		 <strong><span style="color:#333; font-size:1.2em">Don't have a Mimo account? <a href="https://staging.mimo.com.ng/users/sign_up" target="new"><span style="color:#1E7EC8; font-size:1.2em;">Create one now!</span></a><br/></strong></span><br/>				
					<!--<strong>Web + Dollar = Mimo</strong><br/>
					<ul style="float:left;padding-left:20px;list-style-type:disc;">
						<li>Web payments.</li>
						<li>Person-to-person payments.</li>
						<li>Mobile phone payments.</li>
						<li>Free sign up. Free mobile applications. Flat, low fees for recipient.</li>
					</ul>	 -->		
			</div>		
		</li>
    </ul>	
</fieldset>


<script type="text/javascript">
	//<![CDATA[
		$('<?php echo $_code ?>_verify_key_div').hide();
				
		var VKClicked<?php echo $_code ?> = function() {
			var acctid = $F("<?php echo $_code ?>_account_id");
			if (acctid.length < 12 || /[^0-9\-]/.test(acctid)) {
				alert('Invalid Mimo account ID number. Please enter your account number following the pattern : ###-###-####');
			}else{
				checkout.setLoadWaiting('payment');
				new Ajax.Request('<?php echo $this->getUrl('mimo/processing/keyRequest')?>',
				{
					method:'post',
					onComplete: checkout.setLoadWaiting(false),
					onFailure: checkout.ajaxFailure.bind(checkout),
					parameters:{accountid: acctid}
				});
				$('<?php echo $_code ?>_verify_key_div').show();
			}			
		}	

		Event.observe($('<?php echo $_code ?>_verify_key_btn'),'click', VKClicked<?php echo $_code ?>);		
	//]]>
</script>





