<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Dwolla
 * @package    Dwolla (dwolla.com)
 * @copyright  Copyright (c) 2011 Dwolla (https://www.dwolla.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 */
?>
<p><strong><?php echo $this->getMethod()->getTitle() ?></strong></p>
<p>
<?php if ($this->getInfo()->getPoNumber()) { ?>
	<span class="nowrap"><strong>Account ID:</strong> <?php echo $this->htmlEscape($this->getInfo()->getPoNumber()) ?></span><br/>
<?php } ?>


</p>



